### ISSUE TITLE
[SCORING-8] Return empty list  instead of 404 on Summary Endpoint 

### ISSUE THREAD

**Issue by DavidWilliamK** [function-future/function-backend#349]
`findAllSummaryByStudentId` need to return empty list instead of 404 error if the particular student doesn't have any quiz and/or assignment done
![image](https://user-images.githubusercontent.com/42311132/73126626-b1ba6700-3fe7-11ea-9657-018b7091866a.png)

**Comment by oliverrsebastian** [comment]
cc @DavidWilliamK **SOLVED**
